### ISSUE TITLE
MVP Dashboard view in NH Launcher

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/nh-launcher#13]
Desired outcome:

A very basic dashboard displaying the sensemaker configuration inside NH Launcher (Neighbourhood Profile view) with a table view where the CA and members can inspect the NH configuration, more details:

- open page (tab) per mapped resource type
- each page has:
  - first column contains the resource identifier (could even be resource type name + resource hash)
  - second column contains the agent identifier of whoever did the assessment (or method name for objective ones)
  - all other columns are dimensions (subjective, as assessment outputs and objective, as method execution outputs)
  - each row contains an assessment or method execution, resources may appear more than once if they have been assessed by many users
  - the page lists ALL assessments for all dimensions involving that resource type
  - if there are **cultural contexts** defined, they become subtabs for that page, where:
    - a one line description of how that cultural context does the sorting and filtering
    - first column contains the resource identifier (could even be resource type name + resource hash)
    - all other columns are dimensions (subjective, as assessment outputs and objective, as method execution outputs)
    - each row contains the resources sorted and filtered according to the Cultural Context rules, with no duplication
  - if there are **methods** defined, each page lists the method buttons on top, so the CA can run them manually (other members can't for now)

**Comment by adaburrows** [comment]
This is done except for the last line item, because it was never in the mockups. Wahoo!
