### ISSUE TITLE
There is no mapping between ResourceDefs and the underlying DNA that provides the objects

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/nh-launcher#137]
### Current Problem

Currently there is no easy mapping from a resource def to the source DNA. This is required if we want to be able to make bridge calls from the sensemaker to the provider dna so that we can do things like resolve resource entry hashes to their underlying data object. We also have no way of indicating whether a resource is from another happ or some other source external to Holochain.

This would also help with allowing applets to expose resource widgets to be viewed outside of the applet context.

### Proposed Solution

To add a `source` property to `ResourceDef`, like so:
```rust
#[hdk_entry_helper]
#[derive(Clone)]
pub struct ResourceDef {
    pub name: String,
    pub base_types: Vec<AppEntryDef>,
    pub dimension_ehs: Vec<EntryHash>,
    pub source: ResourceDefSource,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum ResourceDefSource {
    Dna(DnaHash),
    // can add other source types here, like a website, IPFS, blockchain, etc.
}
```
This way, when we are given a resource eh and a resource def eh, we have everything we need to resolve the resource eh.

There is a function `fetch_provider_resource` in development in https://github.com/neighbour-hoods/sensemaker-lite/pull/50 which aims to resolve a resource eh given the resource eh and the resource def eh.

### Alternatives

another solution, which I may do in the interim to not break the core types, would be to link from the resource def to the source, assuming for not it will always be a `DnaHash`, using a newly created link type `ResourceDefToDnaHash`.

**Comment by weswalla** [comment]
Thoughts @pospi @adaburrows @julioholon @nick-stebbings ?

**Comment by weswalla** [comment]
Related to this too, would be removing the `role_name` property of `AppletConfig`, since in it's current form doesn't make sense and does not support applets made up of multiple DNAs. Rather, having the direct mapping from the resource def to the source DNA (or external source) makes the most sense.

I also wonder of the utility of even having the `AppletConfig` type in the sensemaker. I think a rethinking is imminent. For example, a more simple applet abstraction may suffice. I think the essence of the applet config is simply to know which of the sensemaker primitives are used by / introduced by an applet (which is really just a UI + a .webhapp)

**Comment by adaburrows** [comment]
I'm not sure why it was originally designed this way. I agree with you, but there's some upcoming changes that will make these concerns mostly obsolete. Though, there is the case that we will want to support resources stored externally or over other protocols, but I think it may be reasonable for the provider of the resource to manage that and just provide us with a unique ID that can be used.

The model unfolding basically moves the data out of the applet and out of custom dnas and into our own data storage that acts a bit like a solid pod. It'll use RDF and JSON-LD. That way we can enforce data schemas. It might be interesting to see exactly which definition languages people want to use. Perhaps we also need unvalidated JSON blob storage for some people not ready to define complete data models. But then we will be able to manage the membranes that are used for each space or if we can use capability grants and RBAC in a neighbourhood.

In the case of the external data, we'd basically need to map between an app (likely a web address or EntryHash), the resource schema (likely a web address or EntryHash), and the resource ID (though we may need a protocol if we want to access the data outside of the app). Then the app could fetch the data itself over a postMessage interface to pass back into the Neighbourhood. Given that triplet, we can also cleanly associate an assessment with a resource.

However, I do want to point out that while much of the data in the applet config and resource def are redundant and poorly thought out, we can construct a mapping between the installed_app_id, `Applet::dnaHashes`, the role, and the entry def index and we´d be able to create the correct clients to access data across different Neighbourhoods.
For more info on how this is stored in the current data model in the Matrix, see: https://hackmd.io/@adaburrows/rkQ3cF6Ma

However, as discussed above, much of this is subject to change. I'll probably close this soon as we add more tickets to the UX and Architecture backlogs.

**Comment by adaburrows** [comment]
Related to #180
