### ISSUE TITLE
[BUG] multi agent nh-we not seeing each other

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/nh-launcher#14]
Desired outcome: 

Fix a bug with NH Launcher where agents cannot see what each other creates.

Still need to be able to see agents on the sidebar

**Comment by julioholon** [comment]
Considered deprecated, since agents can already see others updates.
This would be fixed if we update We with latest version of "peer-status" from Holochain Open Dev

**Comment by adaburrows** [comment]
Fixed.
