### ISSUE TITLE
Config for dimensions should be omitted when installing applets

### ISSUE THREAD

**Issue by adaburrows** [neighbour-hoods/nh-launcher#154]
Currently when we install an applet and configure the sensemaker, we pass in the whole of the applet config and go ahead and create the dimensions which are in the config. This should no longer happen.

Extra credit: If an applet has a config for assessment controls, that config is outdated and should be removed. We currently don't have any define config format to associate assessment controls with input dimensions.

**Comment by nick-stebbings** [comment]
> Extra credit: If an applet has a config for assessment controls, that config is outdated and should be removed. We currently don't have any define config format to associate assessment controls with input dimensions.

The feed applet copies your todo applet config so it has the new config format.
