### ISSUE TITLE
[STORY] CA can add a non-configured (L1) applet

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/nh-launcher#25]
As an applet developer I am able to create and test config files on the dashboard for a new happ I care about

Desired outcome:
We have a Wizard that runs on NH launcher, when the CA is installing new applets:
- when installing a Non Configured Applet (level 1), go through these steps to create a brand new config file, that's going to be interacted only from the Dashboard (until the applet UI is changed and it becomes Level 2), and can be exported:
  * Resources: scans applet entry types and allow mapping to ResourceTypes
  * Dimensions: lists available ResourceTypes, and allow mapping to Dimensions
  * Methods: if a dimension is computed, allow defining input dimensions and selecting program (from existing ones)
  * Cultural Contexts: after previous steps are done, create contexts based on existing Dimensions, select sorting and thresholds

**Comment by adaburrows** [comment]
We're not supporting this anymore. Closing.
