### ISSUE TITLE
[DOCS] Documentation on how to create an Example NH

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/nh-launcher#26]
Desired outcome: We have documented (on Gitbook) example neighbourhoods that work with provided applets, explain steps on how to create them.

One example NH, step by step (Software team community? Soccer community?)

**Comment by adaburrows** [comment]
@julioholon, please let me know if you need any other materials or direction on how to use the new interface (granted, it's not fully defined atm, but I can get you a list of terms to start writing about).
