### ISSUE TITLE
CA can add a reconfigurable (L3) applet

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/nh-launcher#29]
As CA I want to install reconfigurable L3 applets to have my members using them, with my  custom changes

Desired outcome:
We have a Wizard that runs on NH laucnher, when the CA is installing new applets:

- when installing a Preconfigured Applet (level 2), go through the Config file in steps to view and validate the structures that are going to be added to the Sensemaker (4 steps: Resources, Dimensions, Methods, Cultural Contexts)
- For L3 applets, edit config within variable ranges set by applet devs

**Comment by julioholon** [comment]
Now instead of editing variable ranges, you bind applet slots with assessment widgets defined by a Sensemaker library

**Comment by adaburrows** [comment]
https://hackmd.io/@adaburrows/SJR2NYMHn

**Comment by adaburrows** [comment]
https://hackmd.io/@adaburrows/HyLSWRsB2

**Comment by adaburrows** [comment]
Breaking this down into new detailed tickets for each task. Also, changing ontology.
