### ISSUE TITLE
Users want to download and run packaged NH

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/nh-launcher#33]
desired outcome: Package NH launcher using Electron and HC Launcher, per architecture decision, for desktop downloadable binary.

For example:
1. alpha testers with the Holochain Launcher can download a nh-laucher.webhapp file from github and install the webhapp manually. Once installed, they can create a group, and install any applet `.webhapp` files manually and interact with the app in a basic way, or;
2. `nh-launcher` is packaged as a standalone desktop app (like acorn) and alpha testers install the app directly from a download link
3. etc...

**Comment by adaburrows** [comment]
We now have a ticket to make a Tauri distribution of this, so this ticket is not necessary.
