### ISSUE TITLE
Switch to pnpm instead of npm

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/nh-launcher#47]
Move to pnpm. It's included in node's corepack and is installed with our nix env. There's not really a good reason to stick with npm, except for some of the ease of configuring workspaces with npm. But really, it shouldn't bee too painful to move the nh-launcher over -- just slightly more complex than the others.

Note that @pospi has completed this for the Sensemaker client in https://github.com/neighbour-hoods/sensemaker-lite/pull/33 (Actually, a few more changes needed to be made in https://github.com/neighbour-hoods/sensemaker-lite/pull/46)

To all repos (sensemaker-lite, applet-template, todo-applet, nh-launcher)

Make sure the workspaces are set up correctly:
* [ ] make a `pnpm-workspace.yaml` file that includes each of the workspace directories.
* [ ] make sure that each `package.json` file has its deps updated. Instead of pointing to a `"file:../client"`, it should point to `"workspace: *"`
* [ ] make sure all `{.,**}/package-lock.json` files are deleted from workspaces.
* [ ] add `package-lock.json` to `.gitignore`.
* [ ] make sure all `{.,**}/node_modules` directories are deleted.
* [ ] reinstall modules with `pnpm i`.
* [ ] double check to make sure everything works.
* [ ] preferably, checkout out the branch in a new clone and test to make sure nothing broke.
* [ ] fix issues that arise in the fresh clone.

**Comment by pospi** [comment]
Hmm sorry @julioholon I was trying to duplicate this to the NH Launcher as a project-specific issue but it looks like you can't do that.

Please clone this issue to any remaining repositories which still need the conversion made? I think I have moved through it for most of the ones I'm working on now.

**Comment by nick-stebbings** [comment]
Merged into develop with #49
