### ISSUE TITLE
Raise the needs for NH Launcher refactor

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/nh-launcher#62]
Document the needs for NH launcher refactor

**Comment by weswalla** [comment]
topics to discuss:
- repo structure
- test coverage
- domain model
- component decoupling
- responsibility modelling

**Comment by weswalla** [comment]
additional topics:
- routing

**Comment by adaburrows** [comment]
TODO: close and make a more in depth set of tickets for this.
