### ISSUE TITLE
[REFACTOR]: Re-evaluate use of lit-context in certain components

### ISSUE THREAD

**Issue by nick-stebbings** [neighbour-hoods/nh-launcher#68]
e.g. `table-filter-map` currently consuming sensemaker and matrix contexts, change to just one.

**Comment by adaburrows** [comment]
@nick-stebbings, could you please elaborate on this and point to where in the code it is currently happening?

**Comment by nick-stebbings** [comment]
@adaburrows Yes looking back on this issue it was created hastily and is vague. In the component mentioned, I believe I missed the fact that `MatrixStore` is now used to fetch a resource view for an assessment, so that makes sense.

The other place was in `with-profile` where it is relying on a `we-group-context` and a `matrix-store` context in order to fetch the correct neighbourhood specific profiles store. Would this be better to just take a `ProfilesStore` type property and get passed the fetched store at the instantiation of the component?

**Comment by nick-stebbings** [comment]
Also maybe this issue is a place to bring up migration to the new context API. Ours is 0.1.1 in the launcher which is very outdated.

**Comment by adaburrows** [comment]
My style prefers using props so we can explicitly see which dependencies are needed, but I really don't mind using contexts when it is well known what the consuming components are. Basically, I prefer as little mystery as possible, whether that be through documentation or parameter passing.

I guess I should probably look at where all this is happening and understand how many components are using this and if it really seems like a big enough problem to need to use the context api for it.

**Comment by adaburrows** [comment]
So actually, I was thinking through the security implications and really, there are things that need to be scoped in the same closure so that all the private information can be shared privately in the closure, but not shared outside of the closure's public interface. Even props could expose too much since they are completely publicly readable by any script loaded up in the browser.

**Comment by adaburrows** [comment]
Closing since this will get shaken out when we implement the new data models and TreeStore.
