### ISSUE TITLE
[BUG]: Sensemaker Store Subscriptions Not Triggering Re-render

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/nh-launcher#70]
Somewhere in #69 sensemaker store subscriptions stopped working. For instance, in the todo applet, when a task item resource is asssessed, the display widget does not update until the page is refreshed. However, in #67 this ability is still functional. This issue thread has been created to track down the nature of this bug.

By deduction, something introduced in #60 or #63 seems to have done it.

**Comment by weswalla** [comment]
After taking a look through #60 I don't see anything suspicious that would cause such a change, so I suspect #63 is where it was introduced.

**Comment by weswalla** [comment]
somehow these lines are causing the issue: https://github.com/neighbour-hoods/nh-launcher/blob/cce858e4cfdd54d243a71744ca9a3e1e19900b90/ui/app/src/elements/components/profile/with-profile.ts#L38-L56

because when I comment them out the issue goes away.

**Comment by pospi** [comment]
Hmm. Your problem *could* be in `firstUpdated()`. I wonder whether calling `_selectedNeighbourhoodProfile` could be crashing due to some race condition with initialising `this._matrixStore` or accessing `this._matrixStore.profilesStore()`.

See mention in comment above^ RE error handling.

**Comment by weswalla** [comment]
I don't think it has to do with `firstUpdated()` but the declaration of the subscribers (I tried commenting out just the `firstUpdated()` method and the same error persisted. I will try wrapping in a try catch block though, as you suggested in your PR comment.

**Comment by adaburrows** [comment]
Given how we merged a whole bunch of stuff from the rebase branch after fixing some issues, is this still an issue that we didn't address?

**Comment by adaburrows** [comment]
It has been addressed. Closing.
