### ISSUE TITLE
[BUG] various interaction rough edges

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/nh-launcher#71]
The design team probably needs to do a review once the dev team is happy with this refactor. They are small bugs, but bad for UX:

- [ ] NH and profile join dialogs force you to select an image. Can they use identicons and make images optional?
- [ ] NH and profile join dialogs fail silently if required fields are not filled out upon submitting
- [ ] The error encountered for "app already installed" is not handled in the UI, so even though reinstalling apps succeeds it appears to the user that the operation has failed

Please collect more here as you come across them :slightly_smiling_face:

**Comment by adaburrows** [comment]
I'd actually prefer each of these to be split out into their own tickets. That way each git commit message can reference the specific ticket number for the bug it fixes.

**Comment by nick-stebbings** [comment]
I have created these as separate issues #77 #78 #79. Please feel free to flesh out/alter
