### ISSUE TITLE
Implement utility components library and Launcher / Applet shared behaviours

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/nh-launcher#82]
This issue involves (or impacts, or possibly follows on from) #73.

There are some high-level Applet development goals we have yet to meet:

- A simple, standards-compliant entrypoint for Applet rendering components to be exposed to the Launcher (mostly discussed in #73)
- Simplified data bindings and API interactions with a `SensemakerStore` (read: minimal boilerplate, as declarative as possible)
- Affordances for lightweight Dimension Widget components that interact with the `SensemakerStore`
- The same library code being used in the Launcher Dashboard as in Applets; i.e. the Dashboard being "just another Applet"
- Future-proofing for the possibility of multiple `SensemakerStores` being provided and passed to Applets by the Launcher

**Comment by pospi** [comment]
11520be1910dc4d6a6410e1eb0715d978b5cd70a shows us what `RenderBlock` could be reduced to- i.e. now all that calling code needs to do is get a handle on a CustomElement class and pass it to `.elementClass`.

Basically I think that this element of #73:

> passing the appropriate Sensemaker attributes to the component

could be handled by shared 'context-binding' (in the generic sense, not an NHs Context) "controller" component. This is a typical pattern in modern reactive webapp development with other examples being [Apollo Elements](https://apolloelements.dev/), various "theme provider" components used in design system libraries and indeed our own custom use of `@lit-labs/context` with Applet Provider websocket connections.

This "controller" component would be rendered by the Launcher to wrap any dynamic `RenderBlock`. Within it, `sensemakerStore` `appletAppInfo` and `appAgentWebsocket` would be assigned via `require('@lit-labs/context').provide` and automatically passed down to Applet & Widget CustomElements. It would also define a well-known set of event listeners which trigger API calls into `sensemakerStore`.

### More on DOM contexts & event bindings

"Lightweight Dimension Widget components" are then just simple CustomElements with some well-defined `properties` and `CustomEvents` to be emitted.

It also sets us up for further iterating on the pattern and potentially being able to declaratively bind a Sensemaker Context to different areas of the page in order to mix & match Contexts in the UI. In such a pattern, any configured Resource Views or Dimension Widgets would automatically re-bind themselves to the appropriately configured EntryHashes based on data from the new Sensemaker Context.

### As applied to the Applet layer

Using the Todo Applet as an example, we should no longer need any of these properties on the `TodoApplet` ('full' renderer) CustomElement:

```ts
  @property()
  appletAppInfo!: AppletInfo[];

  @property()
  appAgentWebsocket!: AppAgentClient;

  @property()
  sensemakerStore!: SensemakerStore;
```

The nice thing is we don't have to define them as `require('@lit-labs/context').consume` either, so we can remove this boilerplate. We could instead use a single directive to [attach `ContextConsumer` controllers](https://www.npmjs.com/package/@lit-labs/context#consuming-a-context) and provide helper instance method(s) to extract the necessary parameters for constructing general-case Provider Stores in `firstUpdated`. Probably the only parameter needed to infer these parameters for most Applets is the `roleName` of the associated Holochain Cell.

**TBC whether we should hardcode these role IDs in the Applet code or how else they could be defined or provided by the Launcher.** For hREA-based apps there are certainly many `roleNames` to be parsed but this can still easily be done with access to `appletAppInfo`.

The `TodoApplet` is then only responsible for passing these returned parameters to its own (domain specific) `TodoStore` constructor and the rest of this initialisation complexity can be hidden away.

**Comment by adaburrows** [comment]
Closing this since we will shortly be creating more specific stories that abstract the SensemakerStore away from the applet completely from. These will come from the engineering considerations from the new stories in the Miro board.
