### ISSUE TITLE
Implement Initial Pass For Assessment Tray Feature

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/nh-launcher#87]
steps:

- [ ] expose element classes from applet interface directly
- [ ] update widget configuration to include valid ranges
- [ ] create tray component that can add/remove dimensions and configure a matching widget for each dimension
- [ ] cover core functionality with descriptive tests

**Comment by adaburrows** [comment]
I'm going to split this out into several more well defined tickets.
