### ISSUE TITLE
[BUG] Resource render in the Dashboard is intermittently receiving and outputting the wrong Resource names

### ISSUE THREAD

**Issue by nick-stebbings** [neighbour-hoods/nh-launcher#94]
Steps to reproduce (I suggest using the `feature/nh-home-styles` branch if it has not yet had PR completed yet)

- Join a NH, create a profile, install Todo Applet
- Create a list and two list items with different names
- Assess each resource with different values so you can tell them apart
- Go to dashboard
- See the subjective assessments on the default tab do not necessarily have the correct resource names as the ones that you assessed
- Change to a context tab and compare the resource names there
- If you go back and forth to the applet you may get different results.

**Comment by nick-stebbings** [comment]
I did some digging into this today as it tarnishes the demo a bit having the wrong resource names rendered. Be good to get it fixed by then.

I discovered:
After the assessments are filtered, down to 2, it seems the resource renderer is called 2 times for each assessment ( not sure why ).

I added console.logs into the `task-display-wrapper` in the Todo applet and this is what I got. I have pointed out where the hash that is  received as a property by the component differs from the entry/description expected for that hash.

@weswalla could this be an error in `get_latest_task_with_eh` zome fn?

![image](https://github.com/neighbour-hoods/nh-launcher/assets/47646783/d37cc28f-de7e-493b-a61e-ae0a22216217)


Anyone have an idea why this would call the `ref` callback twice and execute with different results that never get displayed in the referenced DOM? I was thinking maybe `ref` callbacks are memoised to stop un-needed rerenders. The code that calls the renderer looks like this

```
decorator: (resource: any) => {
          return html`<div
                              style="width: 100%; display: grid;place-content: start center; height: 100%; justify-items: center;"
                              ${typeof resource.eh[1] === 'function' ? ref((e) => e ? resource.eh[1](e as HTMLElement, resource.eh[0]): null) : null}
                              > </div>`
}

```

**Comment by nick-stebbings** [comment]
Fixed with commit 5ff8dc10709a6633f16e9e9c228607d1472aef0e 
which also optimises by memoising the resource renderer ref callback

**Comment by nick-stebbings** [comment]
@adaburrows This can be closed now, surely, with all the dashboard and resource renderer updates!

**Comment by adaburrows** [comment]
Closing since we rewrote so much and I don't think we've seen it since.
