### ISSUE TITLE
Global dimension configuration screen

### ISSUE THREAD

**Issue by adaburrows** [neighbour-hoods/nh-launcher#96]
A new screen should be added to the launcher that configure dimensions per Neighbourhood. It should:
- [x] Have a list of input dimensions.
- [x] Allow adding dimensions to the list of input dimensions.
- [x] Show methods which use the input dimension under the input dimension.
- [ ] Each method should show it's output dimension.
- [x] Allow adding methods under the input dimension.
  - [x] The add method dialog should allow naming the output dimension.
  - [x] The output range can be automatically determined from input dimension and method:
    - [x] If the method is AVG, the range can be the same as the input dimension's range since the math is naturally bounded by the same values.
    - If the method is SUM
      - [x] and the input dimensions range is [0, x], where x is a positive integer the output range will be [0, INF].
      - [x] and the input dimensions range is [x, y], where x is a negative integer and y is a positive integer the output range will be [-INF, INF].
      - [x] and the input dimensions range is [x, 0], where x is a negative integer the output range will be [-INF, 0].
      - the reason why these ranges must be so, is because the limit of an infinite sum of finite values is only guaranteed to converge to a finite value under certain conditions which may not be the case.
- [ ] Display the current configuration.

**Comment by adaburrows** [comment]
Yes, this definitely needs UX feedback, but we'll do that later.

**Comment by nick-stebbings** [comment]
@weswalla @adaburrows @pospi  I have encountered an issue with filtering methods that use a certain input method. The `methodDimensionMapping` method in the MatrixStore is a map of entry hashes, but I see no way of getting them from a zome call (`get_dimensions` just returns the records, no Ehs) to continue.

Can someone give me direction on the best way to do this? Cheers

**Comment by nick-stebbings** [comment]
This is for creating global NH config, so it it just that all dimension entry hashes are currently registered in AppletConfig? So when trying to register outside of this applet paradigm there is no way to do it currently?

For the timebeing I will just do multiple `get_dimension` calls with the Ehs from the `methodDimensionMapping`. This won't scale very well though so seems like we will need an API change to batch get Ehs from the sensemaker.

**Comment by weswalla** [comment]
> This is for creating global NH config, so it it just that all dimension entry hashes are currently registered in AppletConfig? So when trying to register outside of this applet paradigm there is no way to do it currently?

Yeah currently dimensions are bound to an applet in the way they are represented in the sensemaker store, we will want to think about how the applet paradigm shifts as sensemaker primitives can be created directly within the launcher

**Comment by nick-stebbings** [comment]
@adaburrows  I tried to implement these -Inf, +Inf ranges but the API for Range doesn't currently allow it. For the timebeing I set the values to constants in the form
`const MIN_RANGE = -1_000_000;
const MAX_RANGE = 1_000_000;`

which can be switched out for -Inf, +Inf if the API changes to get the functionality described in the spec

**Comment by nick-stebbings** [comment]
@adaburrows  Also I cannot complete the method creation without a `resource_def` entry hash to tie it to. This is another thing that is a consequence of us stepping outside the applet paradigm so I will need more guidance as to how to proceed if this is necessary 
@weswalla

**Comment by adaburrows** [comment]
@nick-stebbings, please get in touch with me and we can look at this together and I can spec out the changes that need to be done. There's lots of opportunity to change things around right now, since we'll be making some major changes anyways. I'm available later today and tomorrow.

**Comment by nick-stebbings** [comment]
@adaburrows  This task is mostly done now with a couple of caveats:

- There is no API in place for a global dimension/method mapping (only for those registered in an applet) or for fetching of methods  with their associated dimension Entry hashes - and so the input dimension list will only show those created and linked in the session.
- The output dimensions attached to methods are not in place for the same reason.

But you should be able to run through creating a range, input dimension, output dimension (with calculated range from input dimension) and method with computation. It will show the range entry hash on the input dimensions' list. Then when you refresh it will be lost.

**Comment by nick-stebbings** [comment]
@adaburrows  Also I am not sure what the last task 
" Display the current configuration." means, so it might need to be broken down. Perhaps I am already doing this I am not sure.

**Comment by adaburrows** [comment]
Just for reference outside of Discord, here's my quick sketch of the UX. It's not fancy, but it gets things done in a fairly straightforward way:
![Sketch for UX for Dimension Config](https://github.com/neighbour-hoods/nh-launcher/assets/102320/5e5c48ec-5cd6-4c10-be4c-5cccd4652028)

**Comment by nick-stebbings** [comment]
Almost done with this on the second go around. Waiting on method api on `sensemaker-lite` to be able to provide the rest of the method details.
