### ISSUE TITLE
Assessment widget tray configuration screen

### ISSUE THREAD

**Issue by adaburrows** [neighbour-hoods/nh-launcher#99]
There should be a new page added to the dashboard (accessible near the page that configures dimensions) which should
- [x] consulted the widget registry to load all the ranges supported by the currently registered components
- [x] have a sidebar listing all of the resource defs available; and
- [x] when a user selects a resource def from the side panel,
  - [x] a form to configure the assessment widget tray should appear; and should:
    - [x] allow adding pairs of dimensions that will show up in the assessment tray
    - [x] load the corresponding ranges for the selected dimensions
    - [x] filter the current selectable widgets to what is supported by the current selected input dimension
    - [x] allow selecting an input widget which is compatible with the range of the selected iput dimension

Currently, we don't hav enough input from design to know much about the output widget. Also, what seems to happen in the AssessmentWidgetTray is that the output is always the same text box.

The configuration should conform to the Assessment Widget Tray configuration API:

```ts
type AssessmentWidgetConfig = {
    dimensionEh: EntryHash,
    widgetEh?: EntryHash // This is specifically for when components are separated out into their own DHT entry (or sequence of DHT entries to allow extra large codebases to be stored).
} | {
    dimensionEh: EntryHash,
    applicationId?: EntryHash, // This is whatever the id for the application is. I didn't check to see if this is accurate
    componentName?: string // This is the name of the component as exposed by the applet interface
}
type AssessmentWidgetBlockConfig = {
    // This is the widget that allows making an assessment and displaying the user's chosen selection if the user can select one of many options
    inputAssessmentWidget: AssessmentWidgetConfig,
    outputAssessmentWidget: {
        dimensionEh: EntryHash
        // There is currently no agreement about having multiple components, one for assessment and one for pure output of computed assessments.
        // However, if there were separate components, the config for that component would go here and this would be the same as above
        // There is also a discussion to be had about other modalities of sensemaking like tags and things we haven't considered yet.
    }
}
// I'm torn between making this an ordered hash or just an array. I think for simplicity, this will be an array.
type AssessmentWidgetTrayConfig = AssessmentWidgetBlockConfig[]
type ResourceDefAssessmentWidgetTrayConfig = {
    [ResourceDefEH]: AssessmentWidgetTrayConfig
}
```

For example, the following would configure two assessment widgets and their output dimensions in an assessment tray for a specific resource def entry hash:
```js
{
  'resource_def_eh': [
    {
      'inputAssessmentWidget': {
        'dimensionEh': 'aefba133716adf244c3eab3590ca...',
        'applicationId': 'app_id',
        'componentName': 'chilli_pepper_scale_assessment_widget'
      },
      'outputAssessmentWidget': {
        'dimensionEh': 'aeda1343216adf233fadbc3eacb3...'
    },
    {
      'inputAssessmentWidget': {
        'dimensionEh': 'acabd1337a6cdf245c3eaaaa90ca...',
        'applicationId': 'app_id',
        'componentName': 'infinite_claps_assessment_widget'
      },
      'outputAssessmentWidget': {
        'dimensionEh': 'acabaaaaaaaaaaaaaaaaaaaaa42a...'
    },
  ]
}
```

**Comment by herramienta-digital** [comment]
We have a mockup for this ready for review:
https://www.figma.com/file/CwUbE97u3jOIe3UC7iiZcy/Neighbourhoods-Design-System?type=design&node-id=1532%3A25538&mode=dev
